In [5]:
import pandas as pd, glob

# Load one station, one product
files = glob.glob("../noaa_data_pipeline/data/coops/station=8518750/product=water_level/**/*.parquet", recursive=True)
df = pd.concat([pd.read_parquet(f) for f in sorted(files)])

print(df.shape)
print(df.isnull().sum())
print(df.describe())
df.head(30)

(2590275, 6)
timestamp           0
station_id          0
product             0
quality_flag        0
value           19504
speed           26536
dtype: int64
                           timestamp         value         speed
count                        2590275  2.570771e+06  2.563739e+06
mean   2011-05-06 20:51:35.309687040  8.717905e-01  4.258387e-02
min              1996-01-01 00:00:00 -1.010000e+00  0.000000e+00
25%              2004-01-05 08:57:00  4.260000e-01  1.600000e-02
50%              2011-05-26 14:12:00  8.800000e-01  3.200000e-02
75%              2018-10-14 19:03:00  1.317000e+00  5.900000e-02
max              2026-03-04 23:54:00  4.284000e+00  4.206000e+00
std                              NaN  5.399595e-01  3.769307e-02

             timestamp station_id      product quality_flag  value  speed
0  1996-01-01 00:00:00    8518750  water_level            v  0.843  0.059
1  1996-01-01 00:06:00    8518750  water_level            v  0.821  0.027
2  1996-01-01 00:12:00    8518750  water_level            v  0.796  0.020
3  1996-01-01 00:18:00    8518750  water_level            v  0.768  0.014
4  1996-01-01 00:24:00    8518750  water_level            v  0.736  0.039
5  1996-01-01 00:30:00    8518750  water_level            v  0.706  0.014
6  1996-01-01 00:36:00    8518750  water_level            v  0.678  0.018
7  1996-01-01 00:42:00    8518750  water_level            v  0.649  0.017
8  1996-01-01 00:48:00    8518750  water_level            v  0.617  0.014
9  1996-01-01 00:54:00    8518750  water_level            v  0.588  0.011
10 1996-01-01 01:00:00    8518750  water_level            v  0.558  0.009
11 1996-01-01 01:06:00    8518750  water_level            v  0.536  0.008
12 1996-01-01 01:12:00    8518750  water_level            v  0.516  0.006
13 1996-01-01 01:18:00    8518750  water_level            v  0.497  0.006
14 1996-01-01 01:24:00    8518750  water_level            v  0.478  0.016
15 1996-01-01 01:30:00    8518750  water_level            v  0.456  0.019
16 1996-01-01 01:36:00    8518750  water_level            v  0.437  0.025
17 1996-01-01 01:42:00    8518750  water_level            v  0.423  0.020
18 1996-01-01 01:48:00    8518750  water_level            v  0.405  0.015
19 1996-01-01 01:54:00    8518750  water_level            v  0.389  0.014
20 1996-01-01 02:00:00    8518750  water_level            v  0.367  0.009
21 1996-01-01 02:06:00    8518750  water_level            v  0.345  0.008
22 1996-01-01 02:12:00    8518750  water_level            v  0.325  0.007
23 1996-01-01 02:18:00    8518750  water_level            v  0.307  0.008
24 1996-01-01 02:24:00    8518750  water_level            v  0.296  0.013
25 1996-01-01 02:30:00    8518750  water_level            v  0.278  0.031
26 1996-01-01 02:36:00    8518750  water_level            v  0.264  0.018
27 1996-01-01 02:42:00    8518750  water_level            v  0.249  0.016
28 1996-01-01 02:48:00    8518750  water_level            v  0.239  0.015
29 1996-01-01 02:54:00    8518750  water_level            v  0.231  0.016

In [10]:
df_by_hour = df[df["timestamp"].dt.minute == 0]
df_by_hour.head(100)

              timestamp station_id      product quality_flag  value  speed
0   1996-01-01 00:00:00    8518750  water_level            v  0.843  0.059
10  1996-01-01 01:00:00    8518750  water_level            v  0.558  0.009
20  1996-01-01 02:00:00    8518750  water_level            v  0.367  0.009
30  1996-01-01 03:00:00    8518750  water_level            v  0.223  0.025
40  1996-01-01 04:00:00    8518750  water_level            v  0.185  0.006
..                  ...        ...          ...          ...    ...    ...
950 1996-01-04 23:00:00    8518750  water_level            v  1.217  0.025
960 1996-01-05 00:00:00    8518750  water_level            v  1.343  0.028
970 1996-01-05 01:00:00    8518750  water_level            v  1.352  0.019
980 1996-01-05 02:00:00    8518750  water_level            v  1.204  0.026
990 1996-01-05 03:00:00    8518750  water_level            v  0.894  0.058

[100 rows x 6 columns]

In [8]:
df_by_hour.isnull().sum()

timestamp          0
station_id         0
product            0
quality_flag       0
value           2465
speed           3338
dtype: int64

In [9]:
df_by_hour.describe()

                           timestamp          value          speed
count                         259028  256563.000000  255690.000000
mean   2011-05-06 20:16:41.706379520       0.869599       0.041412
min              1996-01-01 00:00:00      -1.010000       0.000000
25%              2004-01-05 08:45:00       0.425000       0.016000
50%              2011-05-26 13:30:00       0.877000       0.033000
75%              2018-10-14 18:15:00       1.315000       0.058000
max              2026-03-04 23:00:00       4.263000       2.969000
std                              NaN       0.539079       0.033843

In [11]:
df.tail(100)

              timestamp station_id      product quality_flag  value  speed
860 2026-03-04 14:00:00    8518750  water_level            p  1.587  0.032
861 2026-03-04 14:06:00    8518750  water_level            p  1.586  0.037
862 2026-03-04 14:12:00    8518750  water_level            p  1.573  0.051
863 2026-03-04 14:18:00    8518750  water_level            p  1.573  0.025
864 2026-03-04 14:24:00    8518750  water_level            p  1.561  0.030
..                  ...        ...          ...          ...    ...    ...
955 2026-03-04 23:30:00    8518750  water_level            p  1.069  0.107
956 2026-03-04 23:36:00    8518750  water_level            p  1.104  0.047
957 2026-03-04 23:42:00    8518750  water_level            p  1.146  0.031
958 2026-03-04 23:48:00    8518750  water_level            p  1.176  0.021
959 2026-03-04 23:54:00    8518750  water_level            p  1.205  0.054

[100 rows x 6 columns]

In [ ]:
df_by_hour.